---
- name: Deploy Telegraf role
  hosts: all
  become: True
  remote_user: root
  tasks:
    - import_role:
        name: telegraf
      tags:
        - install
        - configure
        - telegraf
        - start
