---
- name: install | Include RHEL tasks
  ansible.builtin.include_tasks:
    file: install-redhat.yml
  when: ansible_os_family == "RedHat"

- name: install | Include Debian tasks
  ansible.builtin.include_tasks:
    file: install-debian.yml
  when: ansible_os_family == "Debian"
