---
- import_tasks: install-redhat.yml
  when: override_os_family | default(ansible_os_family) == "RedHat"

- import_tasks: install-debian.yml
  when: override_os_family | default(ansible_os_family) == "Debian"
