---
- name: Import RHEL installation tasks
  ansible.builtin.import_tasks: install-redhat.yml
  when: ansible_os_family == "RedHat"

- name: Import Debian/Ubuntu installation tasks
  ansible.builtin.import_tasks: install-debian.yml
  when: ansible_os_family == "Debian"
