---
- import_tasks: install-redhat.yml
  when: ansible_os_family == "RedHat"

- import_tasks: install-debian.yml
  when: ansible_os_family == "Debian"

- name: Enable and start the Telegraf service
  service:
    name: telegraf
    state: started
    enabled: yes
