---
- name: install-debian | Install any necessary dependencies [Debian/Ubuntu]
  ansible.builtin.apt:
    name: "{{ telegraf_dep_pkgs }}"
    state: present
    update_cache: true
    cache_valid_time: 3600

- name: install-debian | Remove old repo file
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/influxdata.list
    state: absent

- name: install-debian | Add InfluxData repository and GPG Key
  ansible.builtin.deb822_repository:
    name: influxdata
    types: deb
    enabled: true
    state: present
    uris: "{{ telegraf_influxdata_base_url }}/{{ ansible_distribution | lower }}"
    suites: "{{ ansible_distribution_release | lower }}"
    components: "{{ telegraf_install_version }}"
    signed_by: "{{ telegraf_influxdata_base_url }}/influxdata-archive_compat.key"

- name: install-debian | Install Telegraf packages [Debian/Ubuntu] # noqa package-latest
  ansible.builtin.apt:
    name: telegraf
    update_cache: true
    state: latest
    autoremove: true
    autoclean: true
  register: telegraf_pkg_install
  until: telegraf_pkg_install is not failed
  retries: 10
  timeout: 60
  delay: 10
  when: telegraf_deb_pkg_url is not defined or telegraf_deb_pkg_url == None
  notify: Restart Telegraf

- name: install-debian | Install downloaded Telegraf package [Debian/Ubuntu]
  ansible.builtin.apt:
    deb: "{{ telegraf_deb_pkg_url }}"
    state: present
    force: true
  register: telegraf_dpkg_install
  until: telegraf_dpkg_install is not failed
  retries: 10
  timeout: 60
  delay: 10
  when: telegraf_deb_pkg_url is defined and telegraf_deb_pkg_url != None
  notify: Restart Telegraf
