---
- name: Install any necessary dependencies [RedHat/CentOS]
  yum:
    name:
      - curl
    state: present

- name: Add InfluxData repository file [RHEL/CentOS]
  yum_repository:
    baseurl: "{{ telegraf_influxdata_base_url }}/rhel/$releasever/$basearch/stable"
    name: influxdb
    description: "InfluxDB Repository"

- name: Install Telegraf packages [RHEL/CentOS]
  yum:
    name: telegraf
    state: latest
    update_cache: yes
