---
- name: Include os specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
    - always

- name: Import installation tasks
  ansible.builtin.include_tasks:
    file: install.yml
    apply:
      tags:
        - telegraf-install
  tags:
    - telegraf

- name: Include statscollection tasks
  ansible.builtin.include_tasks:
    file: statscollection.yml
    apply:
      tags:
        - telegraf-snmp
  tags:
    - telegraf

- name: Import configuration tasks
  ansible.builtin.include_tasks:
    file: configure.yml
    apply:
      tags:
        - telegraf-config
  tags:
    - telegraf

- name: Import service tasks
  ansible.builtin.include_tasks:
    file: start.yml
    apply:
      tags:
        - telegraf-install
        - telegraf-config
  tags:
    - telegraf
