---
- include_tasks: install.yml
  tags: [telegraf, install]

- include_tasks: nvmesh-plugin.yml
  when: "'nvmesh' in group_names"

- include_tasks: statscollection.yml

- include_tasks: configure.yml
  tags: [telegraf, configure]

- include_tasks: start.yml
  tags: [telegraf, start]
  when: telegraf_start_service
