---
- name: Include os specific vars
  ansible.builtin.include_vars: "{{ item }}"

  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_distribution }}.yml"
  tags:
    - always
- name: Import installation tasks
  ansible.builtin.include_tasks:
    file: install.yml
  tags:
    - telegraf
    - telegraf-install
- name: Include nvmesh tasks
  ansible.builtin.include_tasks:
    file: nvmesh-plugin.yml
  when: "'nvmesh' in group_names"
  tags:
    - telegraf-nvmesh
- name: Include statscollection tasks
  ansible.builtin.include_tasks:
    file: statscollection.yml
  tags:
    - telegraf-snmp
- name: Import configuration tasks
  ansible.builtin.include_tasks:
    file: configure.yml
  tags:
    - telegraf
    - telegraf-config

- name: Import service tasks
  ansible.builtin.include_tasks:
    file: start.yml
