---
- name: include os specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags:
       - always
- import_tasks: install.yml
  tags:
    - telegraf
    - telegraf-install

- import_tasks: nvmesh-plugin.yml
  when: "'nvmesh' in group_names"
  tags:
    - telegraf-nvmesh

- import_tasks: statscollection.yml
  tags:
    - telegraf-snmp

- import_tasks: configure.yml
  tags:
    - telegraf
    - telegraf-config

- import_tasks: start.yml