---
- import_tasks: install.yml
  tags: [telegraf, install]

- import_tasks: nvmesh-plugin.yml
  when: "'nvmesh' in group_names"

- import_tasks: statscollection.yml

- import_tasks: configure.yml
  tags: [telegraf, configure]

- import_tasks: start.yml
  tags: [telegraf, start]
  when: telegraf_start_service
