---
- name: Include os specific vars
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "{{ ansible_distribution }}.yml"
  tags:
    - always
- name: Import installation tasks
  ansible.builtin.import_tasks: install.yml
  tags:
    - telegraf
    - telegraf-install
- name: Import SNMP tasks
  ansible.builtin.import_tasks: statscollection.yml
  tags:
    - telegraf-snmp
- name: Import configuration tasks
  ansible.builtin.import_tasks: configure.yml
  tags:
    - telegraf
    - telegraf-config

- name: Import service tasks
  ansible.builtin.import_tasks: start.yml
