---
- name: Add the OS specific varibles
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - always

- import_tasks: install.yml
  tags:
    - telegraf
    - telegraf-install

- import_tasks: nvmesh-plugin.yml
  when: "'nvmesh' in group_names"

- import_tasks: statscollection.yml
  tags:
    - telegraf-snmp

- import_tasks: rsyslog.yml
  when:
    - telegraf_rsyslog_enable
  tags:
    - telegraf-rsyslog

- import_tasks: configure.yml
  tags:
    - telegraf
    - telegraf-config

- import_tasks: start.yml
  tags:
    - always
  when: telegraf_start_service
