---
- include: install.yml
  tags: [telegraf, install]

- include: nvmesh-plugin.yml
  when: "'nvmesh' in group_names"

- include: statscollection.yml

- include: configure.yml
  tags: [telegraf, configure]

- include: start.yml
  tags: [telegraf, start]
  when: telegraf_start_service
