---
- name: Ensure rsyslogd is installed
  package:
    name: rsyslog
    state: present
  when:
    - telegraf_rsyslog_enable

- name: Copy rsyslog config file to enable logging to telegraf
  template:
    src: rsyslog-telegraf.conf.j2
    dest: /etc/rsyslog.d/50-telegraf.conf
    mode: 0755
  when:
    - telegraf_rsyslog_enable
  notify:
    - restart rsyslog
    - restart telegraf
