
- meta: flush_handlers

- name: Restart the telegraf service
  systemd:
    name: telegraf
    state: "{% if telegraf_require_restart | default(False) %}restarted{% else %}started{% endif %}"
    enabled: yes
  register: telegraf_started
  when:
    - telegraf_start_service

- name: pause
  pause:
    seconds: 10
  when:
    - telegraf_start_service
    - telegraf_started.changed

- name: check status
  command: service telegraf status
  register: telegraf_start_attempt
  when: telegraf_start_service
  changed_when: False

- set_fact:
    telegraf_status: "{{ telegraf_start_attempt | regex_search('Active: active (running)', multiline=True, ignorecase=True) }}"

- name: Get telegraf journald logs if service does not appear to be up
  shell: "journalctl -u telegraf --no-page --since '1 min ago'"
  register: telegraf_journal
  when: telegraf_status is false

- debug:
    var: |
      telegraf_journal.stdout_lines
  when: telegraf_start_attempt.failed
  failed_when: telegraf_start_attempt.failed
