---
- name: start | Flush handlers
  ansible.builtin.meta: flush_handlers

- name: start | Start or Restart telegraf service
  ansible.builtin.systemd:
    name: telegraf
    state: restarted
    enabled: true
    daemon_reload: true
  register: telegraf_started
  until: telegraf_started is not failed
  retries: 10
  timeout: 60
  delay: 10
