---
- name: start | Flush handlers
  ansible.builtin.meta: flush_handlers

- name: start | Restart the telegraf service
  ansible.builtin.systemd:
    name: telegraf
    state: "{% if telegraf_require_restart | default(False) %}restarted{% else %}started{% endif %}"
    enabled: true
  register: telegraf_started
  when:
    - telegraf_start_service

- name: start | Pause for start
  ansible.builtin.pause:
    seconds: 10
  when:
    - telegraf_start_service
    - telegraf_started.changed

- name: start | Check service status
  ansible.builtin.command: service telegraf status
  register: telegraf_start_attempt
  changed_when: telegraf_start_attempt is changed
  when:
    - telegraf_start_service
    - telegraf_started.changed

- name: start | Set telegraf_status gather_fact
  ansible.builtin.set_fact:
    telegraf_status: "{{ telegraf_start_attempt | regex_search('Active: active (running)', multiline=True, ignorecase=True) }}"

- name: start | Get telegraf journald logs if service does not appear to be up
  ansible.builtin.command: journalctl -u telegraf --no-page --since '1 min ago'
  register: telegraf_journal
  changed_when: telegraf_journal.changed
  when: telegraf_status is false

- name: start | Print service output
  ansible.builtin.debug:
    var: |
      telegraf_journal.stdout_lines
  when: telegraf_start_attempt.failed
  failed_when: telegraf_start_attempt.failed
