---
- name: statscollection | Install system accounting and reporting packages
  ansible.builtin.package:
    name: "{{ metrics_pkgs }}"
    state: present
  notify:
    - restart_sysstat
    - restart_telegraf

- name: statscollection | Install SNMP Packages
  ansible.builtin.package:
    name: "{{ snmp_pkgs }}"
    state: present
  when:
    - telegraf_enable_snmp
  notify:
    - restart_telegraf

- name: statscollection | Install SNMP MIBs
  ansible.builtin.copy:
    src: mibs/
    dest: /var/lib/snmp/mibs/ietf/
    mode: "0644"
  when: telegraf_enable_snmp
  notify:
    - restart_telegraf

- name: statscollection | Enable sysstat logging
  ansible.builtin.lineinfile:
    path: /etc/default/sysstat
    regexp: ^ENABLED.*
    line: ENABLED="true"
  notify:
    - restart_sysstat
    - restart_telegraf
  when:
    - ansible_os_family == "Debian"

- name: statscollection | Start sysstat service
  ansible.builtin.service:
    name: sysstat
    enabled: true
    state: started
