---
- name: Install system accounting and reporting packages
  package:
    name: "{{ metrics_pkgs }}"
    state: present

- name: Install SNMP Packages
  package:
    name: "{{ snmp_pkgs }}"
    state: present
  when:
    - telegraf_enable_snmp

- name: Install SNMP MIBs
  copy:
    src: "mibs/"
    dest: "/var/lib/snmp/mibs/ietf/"
    mode: 0644
  when:
    telegraf_enable_snmp

- name: enable sysstat logging
  lineinfile:
    path: /etc/default/sysstat
    regexp: '^ENABLED.*'
    line: ENABLED="true"
  notify: restart sysstat
  when:
    - ansible_os_family == "Debian"

- name: Start sysstat service
  service:
    name: sysstat
    enabled: yes
    state: started
