---
- name: Install system accounting and reporting packages
  package:
    name: "{{ metrics_pkgs }}"
    state: present

- name: Install SNMP Packages
  package:
    name: "{{ snmp_pkgs }}"
    state: present

- name: Install SNMP Extras
  copy:
    src: "{{ item }}"
    dest: /var/lib/snmp/mibs/ietf/
    mode: 0644
  with_items:
    - FROGFOOT-RESOURCES-MIB
    - UBNT-MIB
    - UBNT-UniFi-MIB

- name: enable sysstat logging
  lineinfile:
    path: /etc/default/sysstat
    regexp: '^ENABLED.*'
    line: ENABLED="true"
  notify: restart sysstat

- name: Start sysstat service
  service:
    name: sysstat
    enabled: yes
    state: started