---

- name: restart telegraf
  set_fact:
    telegraf_require_restart: True

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
    enabled: yes

- name: restart rsyslog
  serrvice:
    name: rsyslog
    state: restarted
    enabled: yes
